apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mwanina-fe
  name: mwanina-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mwanina-fe
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mwanina-fe
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/devops/mwanina-fe
        name: mwanina-fe
        securityContext:
          runAsUser: 1000680000
          runAsGroup: 1000680000
