apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe-root
  name: fe-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-root
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe-root
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/devops/fe-root
        name: fe-root
        securityContext:
          runAsUser: 1000680000
          runAsGroup: 1000680000
